version: '3.8'

services:
  db:
    image: gopher-postgres-db-image
    build:
      context: .
      dockerfile_inline: FROM postgres:16.3
    container_name: gopher-postgres-db-container
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - backend 
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: gopher-redis-image
    build:
      context: .
      dockerfile_inline: FROM redis:6.2-alpine
    restart: unless-stopped
    container_name: gopher-redis-container
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    image: gopher-redis-commander-image
    build:
      context: .
      dockerfile_inline: FROM rediscommander/redis-commander:latest
    
    container_name: gopher-redis-commander-container
    hostname: redis-commander
    
    environment:
    - REDIS_HOST=redis
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - redis
    restart:
      unless-stopped
  
volumes:
  db-data:

networks:
  backend:
    driver: bridge